const A=id=>document.getElementById(id);const session=()=>localStorage.getItem('permitly_session');const request=async(path,{method='GET',body,token=session()}={})=>{const r=await fetch(path,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||j.message||`HTTP ${r.status}`);return j};const msg=(text,bad=false)=>{const el=A('authMessage')||A('accountMessage');if(el){el.textContent=text;el.className='auth-message show '+(bad?'bad':'ok')}};
function slug(v){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)}
if(A('registerForm')){
 document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));A('registerPane').hidden=b.dataset.authTab!=='register';A('loginPane').hidden=b.dataset.authTab!=='login'});
 A('registerForm').onsubmit=async e=>{e.preventDefault();try{const org=A('regOrg').value;const r=await request('/api/v1/auth/register',{method:'POST',token:null,body:{organizationName:org,organizationSlug:slug(org)+'-'+Date.now().toString().slice(-5),workspaceName:'Production',workspaceSlug:'production',name:A('regName').value,email:A('regEmail').value,password:A('regPassword').value}});localStorage.setItem('permitly_session',r.token);location.href='/account'}catch(e){msg(e.message,true)}};
 A('loginForm').onsubmit=async e=>{e.preventDefault();try{const r=await request('/api/v1/auth/login',{method:'POST',token:null,body:{email:A('loginEmail').value,password:A('loginPassword').value}});localStorage.setItem('permitly_session',r.token);location.href='/account'}catch(e){msg(e.message,true)}};
}
if(A('accountTitle')){
 if(!session())location.href='/signup';
 const openPanel=name=>{document.querySelectorAll('.account-nav,.account-panel').forEach(x=>x.classList.remove('active'));document.querySelector(`[data-account-panel="${name}"]`)?.classList.add('active');A('account-'+name)?.classList.add('active');A('accountTitle').textContent={setup:'Production setup',keys:'API keys',billing:'Billing',webhooks:'Webhooks',audit:'Audit log'}[name]};
 document.querySelectorAll('[data-account-panel]').forEach(n=>n.onclick=()=>{openPanel(n.dataset.accountPanel);if(n.dataset.accountPanel==='billing')loadBilling();if(n.dataset.accountPanel==='audit')loadAudit()});document.querySelectorAll('[data-open-account]').forEach(n=>n.onclick=()=>openPanel(n.dataset.openAccount));A('logout').onclick=()=>{localStorage.removeItem('permitly_session');location.href='/signup'};
 let me;async function boot(){try{me=await request('/api/v1/me');A('accountIdentity').textContent=`${me.user.name} · ${me.context.role}`;}catch(e){localStorage.removeItem('permitly_session');location.href='/signup'}}boot();
 A('agentSetupForm').onsubmit=async e=>{e.preventDefault();try{const r=await request('/api/agents',{method:'POST',body:{name:A('setupAgentName').value,type:A('setupAgentType').value}});msg(`Agent ${r.agent.name} created. Open the product dashboard to issue its first permit.`)}catch(e){msg(e.message,true)}};
 A('createKey').onclick=async()=>{try{const r=await request('/api/v1/api-keys',{method:'POST',body:{name:'Production SDK',role:'admin',environment:'test'}});A('keyResult').innerHTML=`<div class="secret-once"><b>Copy this key now—it will not be shown again.</b><code>${r.key.secret}</code><button onclick="navigator.clipboard.writeText('${r.key.secret}')">Copy</button></div>`}catch(e){msg(e.message,true)}};
 async function loadBilling(){try{const [plans,usage]=await Promise.all([request('/api/v1/billing/plans',{token:null}),request('/api/v1/usage')]);A('usageBadge').textContent=`${usage.usage.decisions||0} decisions this month`;A('plans').innerHTML=Object.entries(plans.plans).map(([name,p])=>`<article class="mini-plan"><h3>${name}</h3><b>${p.monthly==null?'Custom':p.monthly===0?'Free':'$'+p.monthly/100+'/mo'}</b><span>${p.agents===null||p.agents===Infinity?'Unlimited':p.agents} agents</span><span>${p.decisions===null||p.decisions===Infinity?'Unlimited':p.decisions.toLocaleString()} decisions</span>${p.monthly?`<button class="btn" data-plan="${name}">Choose ${name}</button>`:''}</article>`).join('');document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=async()=>{try{const r=await request('/api/v1/billing/checkout',{method:'POST',body:{plan:b.dataset.plan,successUrl:location.origin+'/account?billing=success',cancelUrl:location.href}});location.href=r.url}catch(e){msg(e.message,true)}})}catch(e){msg(e.message,true)}}
 A('webhookForm').onsubmit=async e=>{e.preventDefault();try{const r=await request('/api/v1/webhooks',{method:'POST',body:{url:A('webhookUrl').value,secret:A('webhookSecret').value,events:['receipt.created','approval.requested','incident.created']}});A('webhookResult').innerHTML=`<div class="success-box">Webhook ${r.id} registered and signed with HMAC-SHA256.</div>`}catch(e){msg(e.message,true)}};
 async function loadAudit(){try{const r=await request('/api/v1/audit');A('auditStatus').innerHTML=`<span class="pill ${r.chainValid?'ok':'bad'}">${r.chainValid?'Chain valid':'Tampering detected'}</span>`;A('auditRows').innerHTML=r.items.slice().reverse().map(x=>`<div class="audit-row"><code>${x.hash.slice(0,12)}…</code><div><b>${x.action}</b><span>${x.resourceType} · ${x.resourceId}</span></div><time>${new Date(x.timestamp).toLocaleString()}</time></div>`).join('')||'<div class="empty-state">No audit events.</div>'}catch(e){msg(e.message,true)}}
}
