const base=process.env.APP_ORIGIN||('http:'+'//127.0.0.1:8787');
const request=async(path,{method='GET',token,body}={})=>{const r=await fetch(base+path,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(`${path} ${r.status}: ${JSON.stringify(j)}`);return j};
const suffix=Date.now();
const register=await request('/api/v1/auth/register',{method:'POST',body:{organizationName:'Acme Production',organizationSlug:`acme-${suffix}`,workspaceName:'Production',email:`owner-${suffix}@example.test`,name:'Acme Owner',password:'correct-horse-battery-staple'}});
if(!register.token||!register.workspaceId)throw new Error('registration failed');
const me=await request('/api/v1/me',{token:register.token});
if(me.context.role!=='owner')throw new Error('owner role missing');
const key=await request('/api/v1/api-keys',{method:'POST',token:register.token,body:{name:'Production SDK',role:'admin',environment:'test'}});
if(!key.key.secret.startsWith('ap_test_'))throw new Error('API key missing');
const keyMe=await request('/api/v1/me',{token:key.key.secret});
if(!keyMe.context.apiKeyId)throw new Error('API key auth failed');
const agent=await request('/api/agents',{method:'POST',token:key.key.secret,body:{name:'Tenant DeployBot',type:'devops'}});
if(!agent.agent?.id)throw new Error('tenant agent creation failed');
const agents=await request('/api/agents',{token:key.key.secret});
if(agents.items.length!==1||agents.items[0].workspaceId!==register.workspaceId)throw new Error('tenant isolation failed');
const policy=await request('/api/policies',{method:'POST',token:key.key.secret,body:{name:'Tenant deploy policy',scopes:['deploy:*'],budgetCap:1000,maxPerAction:100,requireHumanAbove:80,rateLimitPerMinute:20,conditions:[]}});
const permit=await request('/api/permits',{method:'POST',token:key.key.secret,body:{agentId:agent.agent.id,policyId:policy.policy.id,scopes:['deploy:*'],budgetCap:1000,maxPerAction:100,requireHumanAbove:80,expiresAt:new Date(Date.now()+3600000).toISOString()}});
const decision=await request('/api/actions/authorize',{method:'POST',token:key.key.secret,body:{permitId:permit.permit.id,agentId:agent.agent.id,scope:'deploy:staging',target:'staging',amount:10,input:'Deploy tenant release'}});
if(decision.evaluation?.decision!=='authorized')throw new Error('tenant authorization failed');
const usage=await request('/api/v1/usage/decision',{method:'POST',token:key.key.secret,body:{}});
if(usage.value!==1)throw new Error('usage metering failed');
const webhook=await request('/api/v1/webhooks',{method:'POST',token:register.token,body:{url:'https://example.test/agentpermit',secret:'whsec_test',events:['receipt.created']}});
if(!webhook.id)throw new Error('webhook registration failed');
const audit=await request('/api/v1/audit',{token:register.token});
if(!audit.chainValid||audit.items.length<2)throw new Error('audit chain failed');
const plans=await request('/api/v1/billing/plans');
if(!plans.plans.team)throw new Error('plans unavailable');
console.log('saas smoke ok',{workspace:register.workspaceId,apiKey:key.key.key_prefix,agent:agent.agent.id,permit:permit.permit.id,receipt:decision.receipt.id,usage:usage.value,auditEvents:audit.items.length,webhook:webhook.id});
